general:
  tester: &tester
    path: C:\Windows\System32\fc.exe
    argument:
      - val: /N
        quote: false
      - val: /W
        quote: false
      - "{output}"
      - "{answer}"
  autodiff: &autodiff
    differ: "{input}.diff"
    file: ["{output}", "{answer}"]
  program: &program
    path: null
  basic: &basic
    program: *program
    test: *tester
    autodiff: *autodiff

single:
  basic: *basic

group:
  groups:
    - data:
        regex:
          - regex: '^(.*)\.[^\.]*'
            operate: [{ type: extract, exact: true, position: [1] }]
        input:
          regex:
            - regex: '.*\.in$'
              operate: [{ type: match, exact: true }]
        answer:
          regex:
            - regex: '.*\.ans$'
              operate: [{ type: match, exact: true }]
      basic: *basic

random:
  stop_on_error: true
  data:
    standard:
      argument: ["{input}", "{answer}"]
  basic:
    program: *program
    test: *tester
